---
booktitle: Proceedings of the Fifteenth International Conference on Artificial Intelligence
  and Statistics
publisher: PMLR
logo: AISTATS12_logo.gif
volume: 22
month: 0
year: '2012'
start: 2012-04-21
end: 2012-04-23
published: 2012-03-21
shortname: AISTATS 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: LawrenceAISTATS2012
cycles: false
editor:
- given: Neil D.
  family: Lawrence
- given: Mark
  family: Girolami
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fifteenth International Conference on Artificial Intelligence and Statistics
    Held in La Palma, Canary Islands on 21-23 April 2012

  Published as Volume 22 by the Proceedings of Machine Learning Research on 21 March 2012.

  Volume Edited by:
    Neil D. Lawrence
    Mark Girolami

  Series Editors:
    Neil D. Lawrence
date_str: 21--23 Apr
url: http://proceedings.mlr.press
baseurl: "/v22"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v22
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Artificial Intelligence and Statistics
  url: 
  location: La Palma, Canary Islands
  dates:
  - 2012-04-21
  - 2012-04-22
  - 2012-04-23
  number: 15
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v22.bib
---
